version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: annttonov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/kittygram_media
    depends_on:
      - db
  frontend:
    image: annttonov/kittygram_frontend
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static
  gateway:
    image: annttonov/kittygram_gateway
    volumes:
      - static:/static
      - media:/static/kittygram_media
    ports:
      - 8080:80